### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by amiltonwong** [ariseff/mapnet#1]
Hi, @seffari ,

When I run main.m, after downloading the streetview images, I got the following error, 
```
Traceback (most recent call last):
  File "dependencies/map_parsing/parse_script.py", line 9, in <module>
    ic = interOSM.get_intersections(mapFile, 'file')
  File "/data/code/mapnet/dependencies/map_parsing/interOSM.py", line 10, in get_intersections
    tree = ET.parse(osm)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 651, in parse
    parser = XMLParser(target=TreeBuilder())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1465, in __init__
    "No module named expat; use SimpleXMLTreeBuilder instead"
ImportError: No module named expat; use SimpleXMLTreeBuilder instead
Error using dlmread (line 138)
Empty format string is not supported at the end of a file.

Error in csvread (line 47)
    m=dlmread(filename, ',', r, c);

Error in gsv_osm_corr (line 37)
intersections = csvread('intersections.txt'); % intersection coordinates

Error in main (line 21)
panos = gsv_osm_corr(files); % see gsv_osm_corr.m for panos struct details
```

Any suggestions to fix this problem? THX~

**Comment by ariseff** [comment]
Try deleting the blank line at the end of intersections.txt. Apparently this can sometimes be an issue for dlmread.

**Comment by amiltonwong** [comment]
The intersections.txt doesn't contain any blank line. The same problem exists. Is that I should install "expat" module?

```
Traceback (most recent call last):
  File "dependencies/map_parsing/parse_script.py", line 9, in <module>
    ic = interOSM.get_intersections(mapFile, 'file')
  File "/data/code/mapnet/dependencies/map_parsing/interOSM.py", line 10, in get_intersections
    tree = ET.parse(osm)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 651, in parse
    parser = XMLParser(target=TreeBuilder())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1465, in __init__
    "No module named expat; use SimpleXMLTreeBuilder instead"
ImportError: No module named expat; use SimpleXMLTreeBuilder instead
Error using dlmread (line 138)
Empty format string is not supported at the end of a file.
```

**Comment by ariseff** [comment]
Does anything get written to your intersections.txt? 

The expat module may not be accessible with your current matlab paths setup. Try running the command `python dependencies/map_parsing/parse_script.py` directly from the terminal instead of through matlab.

**Comment by amiltonwong** [comment]
None, the file intersections.txt is just a blank file, no blank lines also.
When running the command python dependencies/map_parsing/parse_script.py directly from the terminal,
I got: 
```
It took 6.39040899277 seconds to parse the OSM map.
```

**Comment by ariseff** [comment]
Great, so it was a matlab paths issue - the script runs successfully now. 
intersections.txt and allNodes.txt should now be written.
